apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: release
  namespace: falco
spec:
  interval: 24h
  chart:
    spec:
      chart: falco
      version: "9.2.0"
      sourceRef:
        kind: HelmRepository
        name: repository
  install:
    createNamespace: false
  targetNamespace: falco
  values:
    tty: true
    customRules: 
      custom-rules.yaml: |-
        - rule: Write below etc
          desc: An attempt to write to /etc directory
          condition: >
            (evt.type in (open,openat,openat2) and evt.is_open_write=true and fd.typechar='f' and fd.num>=0)
            and fd.name startswith /etc
          output: >
            File below /etc opened for writing |
            file=%fd.name pcmdline=%proc.pcmdline
            gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4]
            evt_type=%evt.type user=%user.name user_uid=%user.uid
            user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath
            parent=%proc.pname command=%proc.cmdline terminal=%proc.tty
          priority: WARNING
          tags: [filesystem, mitre_persistence]
    falcosidekick:
      enabled: true
      webui:
        enabled: true
      config:
        teams:
          webhook: "https://default2d93a51c32d44a10aa44d35dee05cd.44.environment.api.powerplatform.com:443/powerautomate/automations/direct/cu/30/workflows/ed124b63ea304c4f81d3335804d1cd68/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=V7AWqxMhKQpHj7YhuNVheE-JLkt69UEU3agQ5nEIuA8"
          minimumpriority: notice

